name: Auto Deploy and Restart PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSHs
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to AWS Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.184.125.47 << 'EOF'
          APP_DIR=/home/ubuntu/ci_cd
          REPO_URL=https://github.com/mansurjr/CI_CD
          PORT=3001

          if [ -d "$APP_DIR" ]; then
            cd $APP_DIR
            git pull origin main
            npm install
            pm2 restart test
          else
            git clone $REPO_URL $APP_DIR
            cd $APP_DIR
            npm install
            echo "PORT=$PORT" > .env
            pm2 start $APP_DIR/dist/main.js --name test
            pm2 save
          fi
        EOF