name: Deploy

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH and deploy
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Trust the host to avoid interactive fingerprint prompt
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # SSH into server and run deployment script
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~
            APP_DIR="ci_cd_app"

            # Ensure Node.js and PM2 are installed
            if ! command -v node >/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            if ! command -v pm2 >/dev/null; then
              npm install -g pm2
            fi

            if [ -d "$APP_DIR" ]; then
              echo "Folder exists. Updating..."
              cd "$APP_DIR"
              if [ -f CI_CD ]; then
                git pull origin main
                npm install
                pm2 restart CI_CD
              else
                npm install
                npm run build
                echo "PORT=3001" > .env
                pm2 start dist/main.js --name CI_CD
                touch CI_CD
              fi
            else
              echo "Folder does not exist. Cloning..."
              git clone https://github.com/mansurjr/CI_CD.git "$APP_DIR"
              cd "$APP_DIR"
              npm install
              npm run build
              echo "PORT=3001" > .env
              pm2 start dist/main.js --name CI_CD
              touch CI_CD
            fi
          EOF
